config/routes.rb
Rails.application.routes.draw do

  root 'timesheets#index'
  post 'entries/create' => 'entries#create', as: 'entries_path'
  get  'entries/edit/:id' => 'entries#edit', as: 'edit_entry'
  post  'entries/update' => 'entries#update', as: 'update_entry'
  post  'entries/destroy/:id' => 'entries#destroy', as: 'destroy_entry'

  devise_for :users
  devise_for :admin_users, ActiveAdmin::Devise.config
  ActiveAdmin.routes(self)

end

app/models/admin_user.rb
class AdminUser < ActiveRecord::Base
  devise :database_authenticatable, 
         :recoverable, :rememberable, :trackable, :validatable
end

app/models/entry.rb
class Entry < ActiveRecord::Base
  belongs_to :project
  belongs_to :user

  validates_presence_of :project_id
  validates_presence_of :start_time
  validates_presence_of :end_time

  attr_accessor :date
  attr_accessor :gap
  attr_accessor :overlap

  def entry_date
    start_time.to_date
  end

  def gap?
    gap
  end

  def overlap?
    overlap
  end

  def is_filler?
    gap || overlap
  end

  def hours
    (self.end_time - self.start_time) / 60 / 60
  end

  def to_s
    self.start_time.strftime("%m/%d/%y: %H:%M") << self.end_time.strftime(" - %H:%M")
  end

  def self.get_entries_for_week(date = nil)
    week_range = DateRangeService.get_week_range(date)

    # returns all entries within the week_range set above, and includes projects
    # to avoid N+1
    includes(:project).where(entries: {start_time: week_range}).
      order(:start_time).reverse.group_by  { |e| e.start_time.strftime("%A") }
  end

  def self.new_gap
    e = Entry.new
    e.gap = true
    e
  end

  def self.new_overlap
    e = Entry.new
    e.overlap = true
    e
  end

  private

  def self.sort_entries(array_of_entries)
    entries.each.with_index do |e, i|
    end
  end
end

app/models/project.rb
class Project < ActiveRecord::Base
  has_many :entries
  has_many :project_assignments
  has_many :users, through: :project_assignments
end

app/models/project_assignment.rb
class ProjectAssignment < ActiveRecord::Base
  belongs_to :project
  belongs_to :user
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

  has_many :entries
  has_many :project_assignments
  has_many :projects, through: :project_assignments

  def to_s
    self.email
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/entries_controller.rb
class EntriesController < ApplicationController
  before_action :authenticate_user!
  before_action :set_entry,       only: [:create]
  before_action :set_entry_by_id, only: [:edit, :update, :destroy]

  def create
    # Becuase the date is passed from the form separately from the start_time
    # and end_time, some preprocessing is performed on the start_time and end_time
    # params to ensure that the times are saved using the date passed by the form
    # and not the default, which is today's date
    @entry.start_time = process_start_time
    @entry.end_time   = process_end_time

    respond_to do |format|
      if @entry.save
        format.html { return redirect_to root_url, notice: 'Entry successfully created' }
        format.js
        format.json { render json: @entry, status: :created, location: root_url }
      else
        format.js { redirect_to root_url }
        format.html {  redirect_to root_url }
        format.json { render json: @entry.errors, status: :unproccessable_entity }
        #render :json => @entry
      end
    end
  end

  def edit
    @projects = Project.all

    respond_to do |format|
      format.js
    end
  end

  def update
    @entry.start_time = process_start_time
    @entry.end_time   = process_end_time

    @entry.description = description_param
    @entry.project_id  = project_id_param

    respond_to do |format|
      if @entry.save
        format.html { return redirect_to root_url, notice: 'Entry successfully created' }
        format.js
      else
        format.js { redirect_to root_url }
        format.html {  redirect_to root_url }
      end
    end
  end

  def destroy
    respond_to do |format|
      if @entry.destroy
        format.js
        format.html { redirect_to root_url }
      else
        format.js { redirect_to root_url }
        format.html {  redirect_to root_url }
      end
    end
  end

  private

  def set_entry
    @entry = current_user.entries.new(entry_params)
  end

  def set_entry_by_id
    id = params[:id] || params[:entry][:id]
    @entry = current_user.entries.find(id)
  end

  def entry_params
    params.require(:entry).permit(:start_time, :end_time, :project_id, :description)
  end

  def process_start_time
    process_time(start_time.to_s)
  end

  def process_end_time
    process_time(end_time.to_s)
  end

  def process_time(time, date = date_param)
    Chronic.time_class = Time.zone
    Chronic.parse("#{date} at #{time}")
  end

  def project_id_param
    params[:entry][:project_id]
  end

  def description_param
    params[:entry][:description]
  end

  def date_param
    params[:entry][:date]
  end

  def start_time
    params[:entry][:start_time]
  end

  def end_time
    params[:entry][:end_time]
  end
end

app/controllers/timesheets_controller.rb
class TimesheetsController < ApplicationController
  before_action :authenticate_user!

  def index
    @entry = current_user.entries.new
    @entries = current_user.entries.get_entries_for_week(params[:week_ending])
    @entries = ErrorFinder.find_gaps_and_overlaps(@entries)
    @projects = current_user.projects.all
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/entries_helper.rb
module EntriesHelper
end

app/helpers/timesheets_helper.rb
module TimesheetsHelper
end

app/views/application/_nav_bar.html.erb
<nav class="navbar navbar-default">
  <div class="container-fluid">
    <!-- Brand and toggle get grouped for better mobile display -->
    <div class="navbar-header">
      <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1" aria-expanded="false">
        <span class="sr-only">Toggle navigation</span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>
      <a class="navbar-brand" href="#">Timesheet</a>
    </div>

    <!-- Collect the nav links, forms, and other content for toggling -->
    <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
      <ul class="nav navbar-nav navbar-right">
        <li><%= link_to "Logout", destroy_user_session_path, method: :delete %></li>
      </ul>
    </div><!-- /.navbar-collapse -->
  </div><!-- /.container-fluid -->
</nav>

app/views/entries/_entry.html.erb
<% if entry.gap? %>
  <tr class="gap">
    <td colspan="7">Take a break? Cool. Otherwise, update your timesheet</td>
  </tr>
<% elsif entry.overlap? %>
  <tr class="overlap">
    <td colspan="7">There is an overlap in your timesheet! Please review it and make the proper changes</td>
  </tr>
<% else %>
  <tr id="entry_row_<%= entry.id %>">
    <td><%= entry.entry_date %></td>
    <td><%= entry.start_time %></td>
    <td><%= entry.end_time %></td>
    <td><%= entry.hours %></td>
    <td><%= entry.project.name %></td>
    <td><%= entry.description %></td>
    <td><%= link_to "Edit", edit_entry_url(entry), remote: true %> |
      <%= link_to "Delete", destroy_entry_url(entry), data: { confirm: 'Are you sure?' },  method: :post %></td>
  </tr>
<% end %>

app/views/entries/_errors.html.erb
<% if @entry.errors.any? %>
  <section id="errors">
    <h2>Oops!</h2>
    <h3>
      Please fix the following <%= pluralize(@entry.errors.size, "error") %>:
    </h3>
    <ol>
      <% @entry.errors.each do |error| %>
        <li><%= error %></li>
      <% end %>
    </ol>
  </section>
<% end %>

app/views/entries/_form.html.erb
<%= form_for @entry, html: { class: "form-inline" },
  url: {action: 'create', controller: 'entries'}, remote: false do |f| %>
  <div class="form-group">
    <%= f.label      :date %>
    <%= f.text_field :date %>
  </div>
  <div class="form-group">
    <%= f.label      :start_time %>
    <%= f.text_field :start_time %>
  </div>
  <div class="form-group">
    <%= f.label      :end_time %>
    <%= f.text_field :end_time %>
  </div>
  <div class="form-group">
    <%= f.label      :description %>
    <%= f.text_field :description %>
  </div>
  <div class="form-group">
    <%= f.label      :project %>
    <%= f.collection_select :project_id, @projects, :id, :name,
      prompt: "Select a Project" %>
  </div>
  <div class="form-group">
    <%= f.submit %>
  </div>
<% end %>

app/views/entries/_row_form.html.erb
<tr id="entry_row_form_<%= entry.id %>">
<%= form_for entry, url: {action: 'update', controller: 'entries'}, remote: true do |f| %>
      <%= f.hidden_field :id,        form: "edit_entry_#{entry.id}" %>
  <td><%= f.text_field   :date,      form: "edit_entry_#{entry.id}", value: entry.start_time.strftime("%m/%d/%Y") %></td>
  <td><%= f.text_field   :start_time,form: "edit_entry_#{entry.id}" %></td>
  <td><%= f.text_field   :end_time,  form: "edit_entry_#{entry.id}" %></td>
  <td>---</td>
  <td>
    <select name="entry[project_id]" form=<%= "edit_entry_#{entry.id}" %>>
      <%=options_from_collection_for_select(Project.all, :id, :name) %>
      </select>
  </td>
  <td><%= f.text_field :description, form: "edit_entry_#{entry.id}" %></td>
  <td><%= submit_tag   "Done",     form: "edit_entry_#{entry.id}" %></td>
<% end %>
</tr>

app/views/entries/_testing.html.erb
<tr>
  <td>TESTTESTTESETETSETSETSETSETSET</td>
</tr>

app/views/entries/create.js.erb
$("<%= escape_javascript (render @entry) %>").appendTo("#entries");

app/views/entries/destroy.js.erb
$("#entry_row_<%= @entry.id %>").remove();

app/views/entries/edit.js.erb
$("#entry_row_<%= @entry.id %>").replaceWith("<%= j (render partial: 'entries/row_form', locals: {entry: @entry, projects: @projects}) %>");
$('#entry_date').datepicker();

app/views/entries/update.js.erb
$("#entry_row_form_<%= @entry.id %>").replaceWith("<%= j (render partial: 'entries/entry', locals: {entry: @entry}) %>");

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Timesheet</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>
  <div class="wrapper">
    <%= render 'nav_bar' %>
    <%= yield %>
  </div
</body>
</html>

app/views/timesheets/_date_select_form.html.erb
<form>
  <%= select_tag "week_ending", options_for_select(DateRangeService.recent_week_options, params['week_ending']) , onchange: "this.form.submit()"%>
  </select>
</form>

app/views/timesheets/index.html.erb
<div class="blk">
  <% render 'entries/errors', locals: {entry: @entry} %>
</div>

<div class="blk">
  <%= render 'date_select_form' %>
</div>

<div class="blk blk_withLGap">
  <h2>Create a new entry</h2>
  <%= render 'entries/form' %>
</div>

<div class="blk">
  <% if @entries.size.zero? %>
    <h2 class="centered">You don't have any entries logged for this week</h2>
  <% else %>
    <table id="entries">
      <% @entries.each do |day, entry_set| %>
        <tr>
          <td class="day" colspan="7"><%= day %></td>
        </tr>
        <tr>
          <th>Date</th>
          <th>Start Time</th>
          <th>End Time</th>
          <th>Hours</th>
          <th>Project</th>
          <th>Description</th>
          <th>Actions</th>
        </tr>
        <% entry_set.each do |entry|%>
          <%= render entry %>
        <% end %>
      <% end %>
  </table>
  <% end %>
</div>